// <auto-generated />
using System;
using InstrumentoT4E0_29_.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InstrumentoT4E0_29_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240809144622_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("InstrumentoT4E0_29_.Models.EFinalBDT4E0_29", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("acpectD_1")
                        .HasColumnType("longtext");

                    b.Property<string>("acpectD_2")
                        .HasColumnType("longtext");

                    b.Property<string>("acpectD_3")
                        .HasColumnType("longtext");

                    b.Property<string>("acpectD_4")
                        .HasColumnType("longtext");

                    b.Property<string>("acpectD_5")
                        .HasColumnType("longtext");

                    b.Property<string>("acpectD_6")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectDCaract_1")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectDCaract_2")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectDCaract_3")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectDCaract_4")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectDCaract_5")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectDCaract_6")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectDProf_1")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectDProf_2")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectDProf_3")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectDProf_4")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectDProf_5")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectDProf_6")
                        .HasColumnType("longtext");

                    b.Property<string>("ayudaFrecuencia_1")
                        .HasColumnType("longtext");

                    b.Property<string>("ayudaFrecuencia_2")
                        .HasColumnType("longtext");

                    b.Property<string>("ayudaFrecuencia_3")
                        .HasColumnType("longtext");

                    b.Property<string>("ayudaRecomienda_1")
                        .HasColumnType("longtext");

                    b.Property<string>("ayudaRecomienda_2")
                        .HasColumnType("longtext");

                    b.Property<string>("ayudaRecomienda_3")
                        .HasColumnType("longtext");

                    b.Property<string>("ayuda_1")
                        .HasColumnType("longtext");

                    b.Property<string>("ayuda_2")
                        .HasColumnType("longtext");

                    b.Property<string>("ayuda_3")
                        .HasColumnType("longtext");

                    b.Property<string>("c10m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c10m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c10m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c10m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c10m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c10m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c10m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c10m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c10m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c11m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c11m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c11m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c11m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c11m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c11m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c11m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c11m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c11m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c12m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c12m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c12m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c12m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c12m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c12m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c12m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c12m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c12m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c13m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c13m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c13m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c13m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c13m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c13m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c13m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c13m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c13m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c14m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c14m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c14m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c14m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c14m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c14m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c14m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c14m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c14m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c1m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c1m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c1m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c1m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c1m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c1m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c1m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c1m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c1m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c2m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c2m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c2m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c2m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c2m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c2m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c2m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c2m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c2m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c3m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c3m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c3m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c3m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c3m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c3m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c3m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c3m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c3m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c4m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c4m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c4m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c4m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c4m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c4m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c4m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c4m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c4m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c5m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c5m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c5m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c5m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c5m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c5m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c5m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c5m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c5m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c6m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c6m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c6m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c6m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c6m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c6m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c6m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c6m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c6m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c7m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c7m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c7m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c7m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c7m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c7m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c7m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c7m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c7m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c8m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c8m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c8m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c8m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c8m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c8m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c8m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c8m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c8m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c9m1")
                        .HasColumnType("longtext");

                    b.Property<string>("c9m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c9m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c9m2")
                        .HasColumnType("longtext");

                    b.Property<string>("c9m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c9m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("c9m3")
                        .HasColumnType("longtext");

                    b.Property<string>("c9m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("c9m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("cambioMarca")
                        .HasColumnType("longtext");

                    b.Property<string>("cambioMarca_ORz")
                        .HasColumnType("longtext");

                    b.Property<string>("cambioMarca_Rz")
                        .HasColumnType("longtext");

                    b.Property<string>("cantPanPref")
                        .HasColumnType("longtext");

                    b.Property<string>("disPag")
                        .HasColumnType("longtext");

                    b.Property<string>("e1m1")
                        .HasColumnType("longtext");

                    b.Property<string>("e1m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e1m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e1m2")
                        .HasColumnType("longtext");

                    b.Property<string>("e1m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e1m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e1m3")
                        .HasColumnType("longtext");

                    b.Property<string>("e1m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e1m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e2m1")
                        .HasColumnType("longtext");

                    b.Property<string>("e2m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e2m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e2m2")
                        .HasColumnType("longtext");

                    b.Property<string>("e2m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e2m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e2m3")
                        .HasColumnType("longtext");

                    b.Property<string>("e2m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e2m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e3m1")
                        .HasColumnType("longtext");

                    b.Property<string>("e3m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e3m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e3m2")
                        .HasColumnType("longtext");

                    b.Property<string>("e3m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e3m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e3m3")
                        .HasColumnType("longtext");

                    b.Property<string>("e3m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e3m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e4m1")
                        .HasColumnType("longtext");

                    b.Property<string>("e4m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e4m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e4m2")
                        .HasColumnType("longtext");

                    b.Property<string>("e4m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e4m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e4m3")
                        .HasColumnType("longtext");

                    b.Property<string>("e4m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e4m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e5m1")
                        .HasColumnType("longtext");

                    b.Property<string>("e5m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e5m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e5m2")
                        .HasColumnType("longtext");

                    b.Property<string>("e5m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e5m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e5m3")
                        .HasColumnType("longtext");

                    b.Property<string>("e5m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e5m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e6m1")
                        .HasColumnType("longtext");

                    b.Property<string>("e6m1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e6m1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e6m2")
                        .HasColumnType("longtext");

                    b.Property<string>("e6m2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e6m2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("e6m3")
                        .HasColumnType("longtext");

                    b.Property<string>("e6m3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("e6m3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("eOm1")
                        .HasColumnType("longtext");

                    b.Property<string>("eOm1_n")
                        .HasColumnType("longtext");

                    b.Property<string>("eOm1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("eOm1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("eOm2")
                        .HasColumnType("longtext");

                    b.Property<string>("eOm2_n")
                        .HasColumnType("longtext");

                    b.Property<string>("eOm2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("eOm2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("eOm3")
                        .HasColumnType("longtext");

                    b.Property<string>("eOm3_n")
                        .HasColumnType("longtext");

                    b.Property<string>("eOm3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("eOm3_rz2")
                        .HasColumnType("longtext");

                    b.Property<int?>("edadBb")
                        .HasColumnType("int");

                    b.Property<string>("expComPan")
                        .HasColumnType("longtext");

                    b.Property<string>("expM1")
                        .HasColumnType("longtext");

                    b.Property<string>("expM2")
                        .HasColumnType("longtext");

                    b.Property<string>("expM3")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("fechaEntrevista_final")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("fechaNacBb")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("fechaUltimoControl")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("incomp1")
                        .HasColumnType("longtext");

                    b.Property<string>("incomp1_rz")
                        .HasColumnType("longtext");

                    b.Property<string>("incomp2")
                        .HasColumnType("longtext");

                    b.Property<string>("incomp2_rz")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_ben1")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_ben2")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_ben3")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_ben4")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_ben5")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_ben6")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_ben7")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_benotro")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_def_ben1")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_def_ben2")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_def_ben3")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_def_ben4")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_def_ben5")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_def_ben6")
                        .HasColumnType("longtext");

                    b.Property<string>("jdua_def_ben7")
                        .HasColumnType("longtext");

                    b.Property<string>("jerarquiaD_1")
                        .HasColumnType("longtext");

                    b.Property<string>("jerarquiaD_2")
                        .HasColumnType("longtext");

                    b.Property<string>("jerarquiaD_3")
                        .HasColumnType("longtext");

                    b.Property<string>("jerarquiaD_4")
                        .HasColumnType("longtext");

                    b.Property<string>("jerarquiaD_5")
                        .HasColumnType("longtext");

                    b.Property<string>("jerarquiaD_6")
                        .HasColumnType("longtext");

                    b.Property<string>("marc_Toalli")
                        .HasColumnType("longtext");

                    b.Property<string>("nom_ref_1")
                        .HasColumnType("longtext");

                    b.Property<string>("nom_ref_2")
                        .HasColumnType("longtext");

                    b.Property<string>("nom_ref_3")
                        .HasColumnType("longtext");

                    b.Property<string>("nom_ref_4")
                        .HasColumnType("longtext");

                    b.Property<string>("num_ref_1")
                        .HasColumnType("longtext");

                    b.Property<string>("num_ref_2")
                        .HasColumnType("longtext");

                    b.Property<string>("num_ref_3")
                        .HasColumnType("longtext");

                    b.Property<string>("num_ref_4")
                        .HasColumnType("longtext");

                    b.Property<string>("obs_ref_1")
                        .HasColumnType("longtext");

                    b.Property<string>("obs_ref_2")
                        .HasColumnType("longtext");

                    b.Property<string>("obs_ref_3")
                        .HasColumnType("longtext");

                    b.Property<string>("obs_ref_4")
                        .HasColumnType("longtext");

                    b.Property<string>("ombligo")
                        .HasColumnType("longtext");

                    b.Property<string>("ombligo_recom")
                        .HasColumnType("longtext");

                    b.Property<string>("ombligo_recomrz")
                        .HasColumnType("longtext");

                    b.Property<string>("ombligo_recprof")
                        .HasColumnType("longtext");

                    b.Property<string>("ombligo_rz")
                        .HasColumnType("longtext");

                    b.Property<string>("oportunidad")
                        .HasColumnType("longtext");

                    b.Property<string>("panPrevios")
                        .HasColumnType("longtext");

                    b.Property<string>("panPrevios1_adq")
                        .HasColumnType("longtext");

                    b.Property<string>("panPrevios1_marcas")
                        .HasColumnType("longtext");

                    b.Property<string>("panPrevios1_marcasRec")
                        .HasColumnType("longtext");

                    b.Property<string>("panPrevios1_marcasRecRz")
                        .HasColumnType("longtext");

                    b.Property<string>("panPrevios1_marcasRz")
                        .HasColumnType("longtext");

                    b.Property<string>("panSiPrevios_adq")
                        .HasColumnType("longtext");

                    b.Property<string>("participante")
                        .HasColumnType("longtext");

                    b.Property<string>("peso_2")
                        .HasColumnType("longtext");

                    b.Property<string>("pref")
                        .HasColumnType("longtext");

                    b.Property<string>("pref_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("pref_rz1_1")
                        .HasColumnType("longtext");

                    b.Property<string>("pref_rz1_2")
                        .HasColumnType("longtext");

                    b.Property<string>("pref_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("pref_rz2_1")
                        .HasColumnType("longtext");

                    b.Property<string>("pref_rz2_2")
                        .HasColumnType("longtext");

                    b.Property<string>("pref_rz3")
                        .HasColumnType("longtext");

                    b.Property<string>("pref_rz3_1")
                        .HasColumnType("longtext");

                    b.Property<string>("pref_rz3_2")
                        .HasColumnType("longtext");

                    b.Property<string>("pref_rz4")
                        .HasColumnType("longtext");

                    b.Property<string>("pref_rz4_1")
                        .HasColumnType("longtext");

                    b.Property<string>("pref_rz4_2")
                        .HasColumnType("longtext");

                    b.Property<string>("prof_obs")
                        .HasColumnType("longtext");

                    b.Property<string>("prof_rec_1")
                        .HasColumnType("longtext");

                    b.Property<string>("prof_rec_2")
                        .HasColumnType("longtext");

                    b.Property<string>("prof_rec_3")
                        .HasColumnType("longtext");

                    b.Property<string>("profesional_3")
                        .HasColumnType("longtext");

                    b.Property<string>("tallaBb")
                        .HasColumnType("longtext");

                    b.Property<string>("tm1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm1_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm1_rz1_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm1_rz1_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm1_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm1_rz2_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm1_rz2_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm1_rz3")
                        .HasColumnType("longtext");

                    b.Property<string>("tm1_rz3_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm1_rz3_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm1_rz4")
                        .HasColumnType("longtext");

                    b.Property<string>("tm1_rz4_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm1_rz4_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm2_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm2_rz1_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm2_rz1_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm2_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm2_rz2_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm2_rz2_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm2_rz3")
                        .HasColumnType("longtext");

                    b.Property<string>("tm2_rz3_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm2_rz3_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm2_rz4")
                        .HasColumnType("longtext");

                    b.Property<string>("tm2_rz4_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm2_rz4_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm3")
                        .HasColumnType("longtext");

                    b.Property<string>("tm3_rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm3_rz1_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm3_rz1_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm3_rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm3_rz2_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm3_rz2_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm3_rz3")
                        .HasColumnType("longtext");

                    b.Property<string>("tm3_rz3_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm3_rz3_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tm3_rz4")
                        .HasColumnType("longtext");

                    b.Property<string>("tm3_rz4_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tm3_rz4_2")
                        .HasColumnType("longtext");

                    b.Property<string>("valDisPag")
                        .HasColumnType("longtext");

                    b.Property<string>("valPanPref")
                        .HasColumnType("longtext");

                    b.Property<string>("val_est")
                        .HasColumnType("longtext");

                    b.Property<string>("val_est_rz")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("EFinalBDT4E0_29");
                });

            modelBuilder.Entity("InstrumentoT4E0_29_.Models.EncuadreBDT4E0_29", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("asoBen_1")
                        .HasColumnType("longtext");

                    b.Property<string>("asoBen_2")
                        .HasColumnType("longtext");

                    b.Property<string>("asoBen_3")
                        .HasColumnType("longtext");

                    b.Property<string>("asoBen_4")
                        .HasColumnType("longtext");

                    b.Property<string>("asoBen_5")
                        .HasColumnType("longtext");

                    b.Property<string>("asoBen_6")
                        .HasColumnType("longtext");

                    b.Property<string>("asoBen_Otro")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectCaract_A")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectCaract_B")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectCaract_C")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectCaract_D")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectCaract_E")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectCaract_F")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectProf_A")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectProf_B")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectProf_C")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectProf_D")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectProf_E")
                        .HasColumnType("longtext");

                    b.Property<string>("aspectProf_F")
                        .HasColumnType("longtext");

                    b.Property<string>("aspect_A")
                        .HasColumnType("longtext");

                    b.Property<string>("aspect_B")
                        .HasColumnType("longtext");

                    b.Property<string>("aspect_C")
                        .HasColumnType("longtext");

                    b.Property<string>("aspect_D")
                        .HasColumnType("longtext");

                    b.Property<string>("aspect_E")
                        .HasColumnType("longtext");

                    b.Property<string>("aspect_F")
                        .HasColumnType("longtext");

                    b.Property<string>("barrio")
                        .HasColumnType("longtext");

                    b.Property<string>("ciudad")
                        .HasColumnType("longtext");

                    b.Property<string>("correo_Electronico")
                        .HasColumnType("longtext");

                    b.Property<string>("direccion")
                        .HasColumnType("longtext");

                    b.Property<uint?>("doc_Identidad")
                        .HasColumnType("int unsigned");

                    b.Property<string>("ecivil")
                        .HasColumnType("longtext");

                    b.Property<byte?>("edad")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("edad_1")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("edad_12")
                        .HasColumnType("longtext");

                    b.Property<byte?>("edad_2")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("edad_22")
                        .HasColumnType("longtext");

                    b.Property<byte?>("edad_3")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("edad_32")
                        .HasColumnType("longtext");

                    b.Property<byte?>("edad_4")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("edad_42")
                        .HasColumnType("longtext");

                    b.Property<byte?>("edad_5")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("edad_52")
                        .HasColumnType("longtext");

                    b.Property<string>("escola")
                        .HasColumnType("longtext");

                    b.Property<string>("estrato")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("fecha_Nac_Madre")
                        .HasColumnType("datetime(6)");

                    b.Property<byte?>("jerarBen_1")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("jerarBen_2")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("jerarBen_3")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("jerarBen_4")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("jerarBen_5")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("jerarBen_6")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("jerarBen_Otro")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("jerarquia_A")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("jerarquia_B")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("jerarquia_C")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("jerarquia_D")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("jerarquia_E")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("jerarquia_F")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("marcaPan1")
                        .HasColumnType("longtext");

                    b.Property<string>("marcaPan2")
                        .HasColumnType("longtext");

                    b.Property<string>("marcaPan3")
                        .HasColumnType("longtext");

                    b.Property<string>("marcaPan4")
                        .HasColumnType("longtext");

                    b.Property<string>("marcaPan5")
                        .HasColumnType("longtext");

                    b.Property<string>("marcaPan6")
                        .HasColumnType("longtext");

                    b.Property<string>("marcaPan7")
                        .HasColumnType("longtext");

                    b.Property<byte?>("noHijos")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("nombre_Bebe")
                        .HasColumnType("longtext");

                    b.Property<string>("ocupacion")
                        .HasColumnType("longtext");

                    b.Property<string>("otroNombre")
                        .HasColumnType("longtext");

                    b.Property<string>("participante")
                        .HasColumnType("longtext");

                    b.Property<string>("porfBen_1")
                        .HasColumnType("longtext");

                    b.Property<string>("porfBen_2")
                        .HasColumnType("longtext");

                    b.Property<string>("porfBen_3")
                        .HasColumnType("longtext");

                    b.Property<string>("porfBen_4")
                        .HasColumnType("longtext");

                    b.Property<string>("porfBen_5")
                        .HasColumnType("longtext");

                    b.Property<string>("porfBen_6")
                        .HasColumnType("longtext");

                    b.Property<string>("porfBen_Otro")
                        .HasColumnType("longtext");

                    b.Property<string>("profesional")
                        .HasColumnType("longtext");

                    b.Property<string>("refPan1")
                        .HasColumnType("longtext");

                    b.Property<string>("refPan2")
                        .HasColumnType("longtext");

                    b.Property<string>("refPan3")
                        .HasColumnType("longtext");

                    b.Property<string>("refPan4")
                        .HasColumnType("longtext");

                    b.Property<string>("refPan5")
                        .HasColumnType("longtext");

                    b.Property<string>("refPan6")
                        .HasColumnType("longtext");

                    b.Property<string>("refPan7")
                        .HasColumnType("longtext");

                    b.Property<string>("rzNoUsoPanM1")
                        .HasColumnType("longtext");

                    b.Property<string>("rzNoUsoPanM2")
                        .HasColumnType("longtext");

                    b.Property<string>("rzNoUsoPanM3")
                        .HasColumnType("longtext");

                    b.Property<string>("rzNoUsoPanM4")
                        .HasColumnType("longtext");

                    b.Property<string>("rzNoUsoPanM5")
                        .HasColumnType("longtext");

                    b.Property<string>("rzNoUsoPanM6")
                        .HasColumnType("longtext");

                    b.Property<string>("rzNoUsoPanM7")
                        .HasColumnType("longtext");

                    b.Property<string>("sexo")
                        .HasColumnType("longtext");

                    b.Property<string>("sexo_1")
                        .HasColumnType("longtext");

                    b.Property<string>("sexo_2")
                        .HasColumnType("longtext");

                    b.Property<string>("sexo_3")
                        .HasColumnType("longtext");

                    b.Property<string>("sexo_4")
                        .HasColumnType("longtext");

                    b.Property<string>("sexo_5")
                        .HasColumnType("longtext");

                    b.Property<string>("telefono1")
                        .HasColumnType("longtext");

                    b.Property<string>("telefono2")
                        .HasColumnType("longtext");

                    b.Property<string>("usarPanM1")
                        .HasColumnType("longtext");

                    b.Property<string>("usarPanM2")
                        .HasColumnType("longtext");

                    b.Property<string>("usarPanM3")
                        .HasColumnType("longtext");

                    b.Property<string>("usarPanM4")
                        .HasColumnType("longtext");

                    b.Property<string>("usarPanM5")
                        .HasColumnType("longtext");

                    b.Property<string>("usarPanM6")
                        .HasColumnType("longtext");

                    b.Property<string>("usarPanM7")
                        .HasColumnType("longtext");

                    b.Property<string>("usoPanM1")
                        .HasColumnType("longtext");

                    b.Property<string>("usoPanM2")
                        .HasColumnType("longtext");

                    b.Property<string>("usoPanM3")
                        .HasColumnType("longtext");

                    b.Property<string>("usoPanM4")
                        .HasColumnType("longtext");

                    b.Property<string>("usoPanM5")
                        .HasColumnType("longtext");

                    b.Property<string>("usoPanM6")
                        .HasColumnType("longtext");

                    b.Property<string>("usoPanM7")
                        .HasColumnType("longtext");

                    b.Property<string>("usuaria")
                        .HasColumnType("longtext");

                    b.Property<string>("usuariaORz")
                        .HasColumnType("longtext");

                    b.Property<string>("usuariaRz")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("EncuadreBDT4E0_29");
                });

            modelBuilder.Entity("InstrumentoT4E0_29_.Models.MonadicaBDT4E0_29", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cantDiaM1_1")
                        .HasColumnType("longtext");

                    b.Property<string>("cantDiaM1_2")
                        .HasColumnType("longtext");

                    b.Property<string>("cantDiaM1_3")
                        .HasColumnType("longtext");

                    b.Property<string>("cantDiaM2_1")
                        .HasColumnType("longtext");

                    b.Property<string>("cantDiaM2_2")
                        .HasColumnType("longtext");

                    b.Property<string>("cantDiaM2_3")
                        .HasColumnType("longtext");

                    b.Property<string>("cantDiaM3_1")
                        .HasColumnType("longtext");

                    b.Property<string>("cantDiaM3_2")
                        .HasColumnType("longtext");

                    b.Property<string>("cantDiaM3_3")
                        .HasColumnType("longtext");

                    b.Property<string>("cantNocheM1_1")
                        .HasColumnType("longtext");

                    b.Property<string>("cantNocheM1_2")
                        .HasColumnType("longtext");

                    b.Property<string>("cantNocheM1_3")
                        .HasColumnType("longtext");

                    b.Property<string>("cantNocheM2_1")
                        .HasColumnType("longtext");

                    b.Property<string>("cantNocheM2_2")
                        .HasColumnType("longtext");

                    b.Property<string>("cantNocheM2_3")
                        .HasColumnType("longtext");

                    b.Property<string>("cantNocheM3_1")
                        .HasColumnType("longtext");

                    b.Property<string>("cantNocheM3_2")
                        .HasColumnType("longtext");

                    b.Property<string>("cantNocheM3_3")
                        .HasColumnType("longtext");

                    b.Property<string>("filM1Carct")
                        .HasColumnType("longtext");

                    b.Property<string>("filM1Niv")
                        .HasColumnType("longtext");

                    b.Property<string>("filM1lgr")
                        .HasColumnType("longtext");

                    b.Property<string>("filM2Carct")
                        .HasColumnType("longtext");

                    b.Property<string>("filM2Niv")
                        .HasColumnType("longtext");

                    b.Property<string>("filM2lgr")
                        .HasColumnType("longtext");

                    b.Property<string>("filM3Carct")
                        .HasColumnType("longtext");

                    b.Property<string>("filM3Niv")
                        .HasColumnType("longtext");

                    b.Property<string>("filM3lgr")
                        .HasColumnType("longtext");

                    b.Property<string>("filtM1")
                        .HasColumnType("longtext");

                    b.Property<string>("filtM1Mom_1")
                        .HasColumnType("longtext");

                    b.Property<string>("filtM1Mom_2")
                        .HasColumnType("longtext");

                    b.Property<byte?>("filtM1No")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("filtM1Tipo")
                        .HasColumnType("longtext");

                    b.Property<string>("filtM2")
                        .HasColumnType("longtext");

                    b.Property<string>("filtM2Mom_1")
                        .HasColumnType("longtext");

                    b.Property<string>("filtM2Mom_2")
                        .HasColumnType("longtext");

                    b.Property<byte?>("filtM2No")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("filtM2Tipo")
                        .HasColumnType("longtext");

                    b.Property<string>("filtM3")
                        .HasColumnType("longtext");

                    b.Property<string>("filtM3Mom_1")
                        .HasColumnType("longtext");

                    b.Property<string>("filtM3Mom_2")
                        .HasColumnType("longtext");

                    b.Property<byte?>("filtM3No")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("filtM3Tipo")
                        .HasColumnType("longtext");

                    b.Property<string>("irriCaractM1")
                        .HasColumnType("longtext");

                    b.Property<string>("irriCaractM2")
                        .HasColumnType("longtext");

                    b.Property<string>("irriCaractM3")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM1")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM1Part_1")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM1Part_2")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM1Part_3")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM1Zon_1")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM1Zon_2")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM1Zon_3")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM2")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM2Part_1")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM2Part_2")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM2Part_3")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM2Zon_1")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM2Zon_2")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM2Zon_3")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM3")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM3Part_1")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM3Part_2")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM3Part_3")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM3Zon_1")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM3Zon_2")
                        .HasColumnType("longtext");

                    b.Property<string>("irriM3Zon_3")
                        .HasColumnType("longtext");

                    b.Property<string>("obsProM1")
                        .HasColumnType("longtext");

                    b.Property<string>("obsProM2")
                        .HasColumnType("longtext");

                    b.Property<string>("obsProM3")
                        .HasColumnType("longtext");

                    b.Property<byte?>("odenUsoM1")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("odenUsoM2")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("odenUsoM3")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("panM1Dur_1")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_10")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_11")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_12")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_13")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_14")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_15")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_16")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_17")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_18")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_2")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_3")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_4")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_5")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_6")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_7")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_8")
                        .HasColumnType("longtext");

                    b.Property<string>("panM1Dur_9")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_1")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_10")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_11")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_12")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_13")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_14")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_15")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_16")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_17")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_18")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_2")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_3")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_4")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_5")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_6")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_7")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_8")
                        .HasColumnType("longtext");

                    b.Property<string>("panM2Dur_9")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_1")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_10")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_11")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_12")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_13")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_14")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_15")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_16")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_17")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_18")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_2")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_3")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_4")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_5")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_6")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_7")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_8")
                        .HasColumnType("longtext");

                    b.Property<string>("panM3Dur_9")
                        .HasColumnType("longtext");

                    b.Property<string>("participante")
                        .HasColumnType("longtext");

                    b.Property<string>("profesional_2")
                        .HasColumnType("longtext");

                    b.Property<string>("semM1")
                        .HasColumnType("longtext");

                    b.Property<string>("semM1A")
                        .HasColumnType("longtext");

                    b.Property<byte?>("semM1Ben1")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM1Ben2")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM1Ben3")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM1Ben4")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM1Ben5")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM1Ben6")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM1BenOtro")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("semM1BenOtroN")
                        .HasColumnType("longtext");

                    b.Property<string>("semM1Rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("semM1Rz1_1")
                        .HasColumnType("longtext");

                    b.Property<string>("semM1Rz1_2")
                        .HasColumnType("longtext");

                    b.Property<string>("semM1Rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("semM1Rz2_1")
                        .HasColumnType("longtext");

                    b.Property<string>("semM1Rz2_2")
                        .HasColumnType("longtext");

                    b.Property<string>("semM1Rz3")
                        .HasColumnType("longtext");

                    b.Property<string>("semM1Rz3_1")
                        .HasColumnType("longtext");

                    b.Property<string>("semM1Rz3_2")
                        .HasColumnType("longtext");

                    b.Property<string>("semM2")
                        .HasColumnType("longtext");

                    b.Property<string>("semM2A")
                        .HasColumnType("longtext");

                    b.Property<byte?>("semM2Ben1")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM2Ben2")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM2Ben3")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM2Ben4")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM2Ben5")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM2Ben6")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM2BenOtro")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("semM2BenOtroN")
                        .HasColumnType("longtext");

                    b.Property<string>("semM2Rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("semM2Rz1_1")
                        .HasColumnType("longtext");

                    b.Property<string>("semM2Rz1_2")
                        .HasColumnType("longtext");

                    b.Property<string>("semM2Rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("semM2Rz2_1")
                        .HasColumnType("longtext");

                    b.Property<string>("semM2Rz2_2")
                        .HasColumnType("longtext");

                    b.Property<string>("semM2Rz3")
                        .HasColumnType("longtext");

                    b.Property<string>("semM2Rz3_1")
                        .HasColumnType("longtext");

                    b.Property<string>("semM2Rz3_2")
                        .HasColumnType("longtext");

                    b.Property<string>("semM3")
                        .HasColumnType("longtext");

                    b.Property<string>("semM3A")
                        .HasColumnType("longtext");

                    b.Property<byte?>("semM3Ben1")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM3Ben2")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM3Ben3")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM3Ben4")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM3Ben5")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM3Ben6")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("semM3BenOtro")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("semM3BenOtroN")
                        .HasColumnType("longtext");

                    b.Property<string>("semM3Rz1")
                        .HasColumnType("longtext");

                    b.Property<string>("semM3Rz1_1")
                        .HasColumnType("longtext");

                    b.Property<string>("semM3Rz1_2")
                        .HasColumnType("longtext");

                    b.Property<string>("semM3Rz2")
                        .HasColumnType("longtext");

                    b.Property<string>("semM3Rz2_1")
                        .HasColumnType("longtext");

                    b.Property<string>("semM3Rz2_2")
                        .HasColumnType("longtext");

                    b.Property<string>("semM3Rz3")
                        .HasColumnType("longtext");

                    b.Property<string>("semM3Rz3_1")
                        .HasColumnType("longtext");

                    b.Property<string>("semM3Rz3_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM1")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM1Part_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM1Part_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM1Part_3")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM1Tipo_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM1Tipo_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM1Tipo_3")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM2")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM2Part_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM2Part_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM2Part_3")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM2Tipo_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM2Tipo_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM2Tipo_3")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM3")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM3Part_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM3Part_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM3Part_3")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM3Tipo_1")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM3Tipo_2")
                        .HasColumnType("longtext");

                    b.Property<string>("tamM3Tipo_3")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("MonadicaBDT4E0_29");
                });
#pragma warning restore 612, 618
        }
    }
}
