namespace InstrumentoT4E0_29_.Models
{
    public class EFinalBDT4E0_29
    {
        public int id { get; set; }
        public string? profesional_3 { get; set; }
        public string? participante { get; set; }
        public DateTime? fechaEntrevista_final { get; set; }
        public DateTime? fechaNacBb { get; set; }
        public int? edadBb { get; set; }
        public string? tallaBb { get; set; }
        public string? peso_2 { get; set; }
        public DateTime? fechaUltimoControl { get; set; }
        public string? marc_Toalli { get; set; }
        public string? ayuda_1 { get; set; }
        public string? ayudaFrecuencia_1 { get; set; }
        public string? ayudaRecomienda_1 { get; set; }
        public string? ayuda_2 { get; set; }
        public string? ayudaFrecuencia_2 { get; set; }
        public string? ayudaRecomienda_2 { get; set; }
        public string? ayuda_3 { get; set; }
        public string? ayudaFrecuencia_3 { get; set; }
        public string? ayudaRecomienda_3 { get; set; }
        public string? cambioMarca { get; set; }
        public string? cambioMarca_Rz { get; set; }
        public string? cambioMarca_ORz { get; set; }
        public string? tm1 { get; set; }
        public string? tm1_rz1 { get; set; }
        public string? tm1_rz1_1 { get; set; }
        public string? tm1_rz1_2 { get; set; }
        public string? tm1_rz2 { get; set; }
        public string? tm1_rz2_1 { get; set; }
        public string? tm1_rz2_2 { get; set; }
        public string? tm1_rz3 { get; set; }
        public string? tm1_rz3_1 { get; set; }
        public string? tm1_rz3_2 { get; set; }
        public string? tm1_rz4 { get; set; }
        public string? tm1_rz4_1 { get; set; }
        public string? tm1_rz4_2 { get; set; }
        public string? tm2 { get; set; }
        public string? tm2_rz1 { get; set; }
        public string? tm2_rz1_1 { get; set; }
        public string? tm2_rz1_2 { get; set; }
        public string? tm2_rz2 { get; set; }
        public string? tm2_rz2_1 { get; set; }
        public string? tm2_rz2_2 { get; set; }
        public string? tm2_rz3 { get; set; }
        public string? tm2_rz3_1 { get; set; }
        public string? tm2_rz3_2 { get; set; }
        public string? tm2_rz4 { get; set; }
        public string? tm2_rz4_1 { get; set; }
        public string? tm2_rz4_2 { get; set; }
        public string? tm3 { get; set; }
        public string? tm3_rz1 { get; set; }
        public string? tm3_rz1_1 { get; set; }
        public string? tm3_rz1_2 { get; set; }
        public string? tm3_rz2 { get; set; }
        public string? tm3_rz2_1 { get; set; }
        public string? tm3_rz2_2 { get; set; }
        public string? tm3_rz3 { get; set; }
        public string? tm3_rz3_1 { get; set; }
        public string? tm3_rz3_2 { get; set; }
        public string? tm3_rz4 { get; set; }
        public string? tm3_rz4_1 { get; set; }
        public string? tm3_rz4_2 { get; set; }
        public string? pref { get; set; }
        public string? pref_rz1 { get; set; }
        public string? pref_rz1_1 { get; set; }
        public string? pref_rz1_2 { get; set; }
        public string? pref_rz2 { get; set; }
        public string? pref_rz2_1 { get; set; }
        public string? pref_rz2_2 { get; set; }
        public string? pref_rz3 { get; set; }
        public string? pref_rz3_1 { get; set; }
        public string? pref_rz3_2 { get; set; }
        public string? pref_rz4 { get; set; }
        public string? pref_rz4_1 { get; set; }
        public string? pref_rz4_2 { get; set; }
        public string? jdua_ben1 { get; set; }
        public string? jdua_ben2 { get; set; }
        public string? jdua_ben3 { get; set; }
        public string? jdua_ben4 { get; set; }
        public string? jdua_ben5 { get; set; }
        public string? jdua_ben6 { get; set; }
        public string? jdua_benotro { get; set; }
        public string? jdua_ben7 { get; set; }
        public string? e1m1 { get; set; }
        public string? e1m1_rz1 { get; set; }
        public string? e1m1_rz2 { get; set; }
        public string? e1m2 { get; set; }
        public string? e1m2_rz1 { get; set; }
        public string? e1m2_rz2 { get; set; }
        public string? e1m3 { get; set; }
        public string? e1m3_rz1 { get; set; }
        public string? e1m3_rz2 { get; set; }
        public string? e2m1 { get; set; }
        public string? e2m1_rz1 { get; set; }
        public string? e2m1_rz2 { get; set; }
        public string? e2m2 { get; set; }
        public string? e2m2_rz1 { get; set; }
        public string? e2m2_rz2 { get; set; }
        public string? e2m3 { get; set; }
        public string? e2m3_rz1 { get; set; }
        public string? e2m3_rz2 { get; set; }
        public string? e3m1 { get; set; }
        public string? e3m1_rz1 { get; set; }
        public string? e3m1_rz2 { get; set; }
        public string? e3m2 { get; set; }
        public string? e3m2_rz1 { get; set; }
        public string? e3m2_rz2 { get; set; }
        public string? e3m3 { get; set; }
        public string? e3m3_rz1 { get; set; }
        public string? e3m3_rz2 { get; set; }
        public string? e4m1 { get; set; }
        public string? e4m1_rz1 { get; set; }
        public string? e4m1_rz2 { get; set; }
        public string? e4m2 { get; set; }
        public string? e4m2_rz1 { get; set; }
        public string? e4m2_rz2 { get; set; }
        public string? e4m3 { get; set; }
        public string? e4m3_rz1 { get; set; }
        public string? e4m3_rz2 { get; set; }
        public string? e5m1 { get; set; }
        public string? e5m1_rz1 { get; set; }
        public string? e5m1_rz2 { get; set; }
        public string? e5m2 { get; set; }
        public string? e5m2_rz1 { get; set; }
        public string? e5m2_rz2 { get; set; }
        public string? e5m3 { get; set; }
        public string? e5m3_rz1 { get; set; }
        public string? e5m3_rz2 { get; set; }
        public string? e6m1 { get; set; }
        public string? e6m1_rz1 { get; set; }
        public string? e6m1_rz2 { get; set; }
        public string? e6m2 { get; set; }
        public string? e6m2_rz1 { get; set; }
        public string? e6m2_rz2 { get; set; }
        public string? e6m3 { get; set; }
        public string? e6m3_rz1 { get; set; }
        public string? e6m3_rz2 { get; set; }
        public string? eOm1_n { get; set; }
        public string? eOm1 { get; set; }
        public string? eOm1_rz1 { get; set; }
        public string? eOm1_rz2 { get; set; }
        public string? eOm2_n { get; set; }
        public string? eOm2 { get; set; }
        public string? eOm2_rz1 { get; set; }
        public string? eOm2_rz2 { get; set; }
        public string? eOm3_n { get; set; }
        public string? eOm3 { get; set; }
        public string? eOm3_rz1 { get; set; }
        public string? eOm3_rz2 { get; set; }
        public string? c1m1 { get; set; }
        public string? c1m1_rz1 { get; set; }
        public string? c1m1_rz2 { get; set; }
        public string? c1m2 { get; set; }
        public string? c1m2_rz1 { get; set; }
        public string? c1m2_rz2 { get; set; }
        public string? c1m3 { get; set; }
        public string? c1m3_rz1 { get; set; }
        public string? c1m3_rz2 { get; set; }
        public string? c2m1 { get; set; }
        public string? c2m1_rz1 { get; set; }
        public string? c2m1_rz2 { get; set; }
        public string? c2m2 { get; set; }
        public string? c2m2_rz1 { get; set; }
        public string? c2m2_rz2 { get; set; }
        public string? c2m3 { get; set; }
        public string? c2m3_rz1 { get; set; }
        public string? c2m3_rz2 { get; set; }
        public string? c3m1 { get; set; }
        public string? c3m1_rz1 { get; set; }
        public string? c3m1_rz2 { get; set; }
        public string? c3m2 { get; set; }
        public string? c3m2_rz1 { get; set; }
        public string? c3m2_rz2 { get; set; }
        public string? c3m3 { get; set; }
        public string? c3m3_rz1 { get; set; }
        public string? c3m3_rz2 { get; set; }
        public string? c4m1 { get; set; }
        public string? c4m1_rz1 { get; set; }
        public string? c4m1_rz2 { get; set; }
        public string? c4m2 { get; set; }
        public string? c4m2_rz1 { get; set; }
        public string? c4m2_rz2 { get; set; }
        public string? c4m3 { get; set; }
        public string? c4m3_rz1 { get; set; }
        public string? c4m3_rz2 { get; set; }
        public string? c5m1 { get; set; }
        public string? c5m1_rz1 { get; set; }
        public string? c5m1_rz2 { get; set; }
        public string? c5m2 { get; set; }
        public string? c5m2_rz1 { get; set; }
        public string? c5m2_rz2 { get; set; }
        public string? c5m3 { get; set; }
        public string? c5m3_rz1 { get; set; }
        public string? c5m3_rz2 { get; set; }
        public string? c6m1 { get; set; }
        public string? c6m1_rz1 { get; set; }
        public string? c6m1_rz2 { get; set; }
        public string? c6m2 { get; set; }
        public string? c6m2_rz1 { get; set; }
        public string? c6m2_rz2 { get; set; }
        public string? c6m3 { get; set; }
        public string? c6m3_rz1 { get; set; }
        public string? c6m3_rz2 { get; set; }
        public string? c7m1 { get; set; }
        public string? c7m1_rz1 { get; set; }
        public string? c7m1_rz2 { get; set; }
        public string? c7m2 { get; set; }
        public string? c7m2_rz1 { get; set; }
        public string? c7m2_rz2 { get; set; }
        public string? c7m3 { get; set; }
        public string? c7m3_rz1 { get; set; }
        public string? c7m3_rz2 { get; set; }
        public string? c8m1 { get; set; }
        public string? c8m1_rz1 { get; set; }
        public string? c8m1_rz2 { get; set; }
        public string? c8m2 { get; set; }
        public string? c8m2_rz1 { get; set; }
        public string? c8m2_rz2 { get; set; }
        public string? c8m3 { get; set; }
        public string? c8m3_rz1 { get; set; }
        public string? c8m3_rz2 { get; set; }
        public string? c9m1 { get; set; }
        public string? c9m1_rz1 { get; set; }
        public string? c9m1_rz2 { get; set; }
        public string? c9m2 { get; set; }
        public string? c9m2_rz1 { get; set; }
        public string? c9m2_rz2 { get; set; }
        public string? c9m3 { get; set; }
        public string? c9m3_rz1 { get; set; }
        public string? c9m3_rz2 { get; set; }
        public string? c10m1 { get; set; }
        public string? c10m1_rz1 { get; set; }
        public string? c10m1_rz2 { get; set; }
        public string? c10m2 { get; set; }
        public string? c10m2_rz1 { get; set; }
        public string? c10m2_rz2 { get; set; }
        public string? c10m3 { get; set; }
        public string? c10m3_rz1 { get; set; }
        public string? c10m3_rz2 { get; set; }
        public string? c11m1 { get; set; }
        public string? c11m1_rz1 { get; set; }
        public string? c11m1_rz2 { get; set; }
        public string? c11m2 { get; set; }
        public string? c11m2_rz1 { get; set; }
        public string? c11m2_rz2 { get; set; }
        public string? c11m3 { get; set; }
        public string? c11m3_rz1 { get; set; }
        public string? c11m3_rz2 { get; set; }
        public string? c12m1 { get; set; }
        public string? c12m1_rz1 { get; set; }
        public string? c12m1_rz2 { get; set; }
        public string? c12m2 { get; set; }
        public string? c12m2_rz1 { get; set; }
        public string? c12m2_rz2 { get; set; }
        public string? c12m3 { get; set; }
        public string? c12m3_rz1 { get; set; }
        public string? c12m3_rz2 { get; set; }
        public string? c13m1 { get; set; }
        public string? c13m1_rz1 { get; set; }
        public string? c13m1_rz2 { get; set; }
        public string? c13m2 { get; set; }
        public string? c13m2_rz1 { get; set; }
        public string? c13m2_rz2 { get; set; }
        public string? c13m3 { get; set; }
        public string? c13m3_rz1 { get; set; }
        public string? c13m3_rz2 { get; set; }
        public string? c14m1 { get; set; }
        public string? c14m1_rz1 { get; set; }
        public string? c14m1_rz2 { get; set; }
        public string? c14m2 { get; set; }
        public string? c14m2_rz1 { get; set; }
        public string? c14m2_rz2 { get; set; }
        public string? c14m3 { get; set; }
        public string? c14m3_rz1 { get; set; }
        public string? c14m3_rz2 { get; set; }
        public string? lug_icom { get; set; }
        public string? icom_1 { get; set; }
        public string? icom_2 { get; set; }
        public string? icom_3 { get; set; }
        public string? icom_4 { get; set; }
        public string? icom_5 { get; set; }
        public string? icom_6 { get; set; }
        public string? icom_rz { get; set; }
        public string? incomp1 { get; set; }
        public string? incomp1_rz { get; set; }
        public string? incomp2 { get; set; }
        public string? incomp2_rz { get; set; }
        public string? panPrevios { get; set; }
        public string? panSiPrevios_adq { get; set; }
        public string? panPrevios1_adq { get; set; }
        public string? panPrevios1_marcas { get; set; }
        public string? panPrevios1_marcasRz { get; set; }
        public string? panPrevios1_marcasRec { get; set; }
        public string? panPrevios1_marcasRecRz { get; set; }
        public string? panPrevios2_adq { get; set; }
        public string? panPrevios2_marcas { get; set; }
        public string? panPrevios2_marcasRz { get; set; }
        public string? panPrevios2_marcasRec { get; set; }
        public string? panPrevios2_marcasRecRz { get; set; }
        public string? panPrevios3_adq { get; set; }
        public string? panPrevios3_marcas { get; set; }
        public string? panPrevios3_marcasRz { get; set; }
        public string? panPrevios3_marcasRec { get; set; }
        public string? panPrevios3_marcasRecRz { get; set; }
        public string? panPrevios4_adq { get; set; }
        public string? panPrevios4_marcas { get; set; }
        public string? panPrevios4_marcasRz { get; set; }
        public string? panPrevios4_marcasRec { get; set; }
        public string? panPrevios4_marcasRecRz { get; set; }
        public string? panPrevios5_adq { get; set; }
        public string? panPrevios5_marcas { get; set; }
        public string? panPrevios5_marcasRz { get; set; }
        public string? panPrevios5_marcasRec { get; set; }
        public string? panPrevios5_marcasRecRz { get; set; }
        public string? expComPan { get; set; }
        public string? cantPanPref { get; set; }
        public string? valPanPref { get; set; }
        public string? disPag { get; set; }
        public string? valDisPag { get; set; }
        public string? expM1 { get; set; }
        public string? expM2 { get; set; }
        public string? expM3 { get; set; }
        public string? oportunidad { get; set; }
        public string? nom_ref_1 { get; set; }
        public string? num_ref_1 { get; set; }
        public string? obs_ref_1 { get; set; }
        public string? nom_ref_2 { get; set; }
        public string? num_ref_2 { get; set; }
        public string? obs_ref_2 { get; set; }
        public string? nom_ref_3 { get; set; }
        public string? num_ref_3 { get; set; }
        public string? obs_ref_3 { get; set; }
        public string? nom_ref_4 { get; set; }
        public string? num_ref_4 { get; set; }
        public string? obs_ref_4 { get; set; }
        public string? val_est { get; set; }
        public string? val_est_rz { get; set; }
        public string? prof_rec_1 { get; set; }
        public string? prof_rec_2 { get; set; }
        public string? prof_rec_3 { get; set; }
        public string? prof_obs { get; set; }
    }
}
