using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace InstrumentoT4E0_29.Models
{
    public class EncuadreBDT4E0_29
    {
        public int id { get; set; }
        public string? profesional { get; set; }
        public string? participante { get; set; }
        public string? ciudad { get; set; }
        public string? barrio { get; set; }
        public string? direccion { get; set; }
        public string? estrato { get; set; }
        public int? edad { get; set; }
        public long? telefono1 { get; set; }
        public long? telefono2 { get; set; }
        public string? usuaria { get; set; }
        public string? usuariaRz { get; set; }
        public string? usuariaORz { get; set; }
        public string? nombre_Bebe { get; set; }
        public string? sexo { get; set; }
        public long? doc_Identidad { get; set; }
        public DateTime? fecha_Nac_Madre { get; set; }
        public string? correo_Electronico { get; set; }
        public string? ecivil { get; set; }
        public string? escola { get; set; }
        public string? ocupacion { get; set; }
        public byte? noHijos { get; set; }
        public string? sexo_1 { get; set; }
        public int? edad_1 { get; set; }
        public string? edad_12 { get; set; }
        public string? sexo_2 { get; set; }
        public int? edad_2 { get; set; }
        public string? edad_22 { get; set; }
        public string? sexo_3 { get; set; }
        public int? edad_3 { get; set; }
        public string? edad_32 { get; set; }
        public string? sexo_4 { get; set; }
        public int? edad_4 { get; set; }
        public string? edad_42 { get; set; }
        public string? sexo_5 { get; set; }
        public int? edad_5 { get; set; }
        public string? edad_52 { get; set; }
        public string? sexo_6 { get; set; }
        public int? edad_6 { get; set; }
        public string? edad_62 { get; set; }
        public string? aspect_A { get; set; }
        public string? aspectProf_A { get; set; }
        public string? aspectCaract_A { get; set; }
        public int? jerarquia_A { get; set; }
        public string? aspect_B { get; set; }
        public string? aspectProf_B { get; set; }
        public string? aspectCaract_B { get; set; }
        public int? jerarquia_B { get; set; }
        public string? aspect_C { get; set; }
        public string? aspectProf_C { get; set; }
        public string? aspectCaract_C { get; set; }
        public int? jerarquia_C { get; set; }
        public string? aspect_D { get; set; }
        public string? aspectProf_D { get; set; }
        public string? aspectCaract_D { get; set; }
        public int? jerarquia_D { get; set; }
        public string? aspect_E { get; set; }
        public string? aspectProf_E { get; set; }
        public string? aspectCaract_E { get; set; }
        public int? jerarquia_E { get; set; }
        public string? aspect_F { get; set; }
        public string? aspectProf_F { get; set; }
        public string? aspectCaract_F { get; set; }
        public int? jerarquia_F { get; set; }
        public string? asoBen_1 { get; set; }
        public int? jerarBen_1 { get; set; }
        public string? porfBen_1 { get; set; }
        public string? asoBen_2 { get; set; }
        public int? jerarBen_2 { get; set; }
        public string? porfBen_2 { get; set; }
        public string? asoBen_3 { get; set; }
        public int? jerarBen_3 { get; set; }
        public string? porfBen_3 { get; set; }
        public string? asoBen_4 { get; set; }
        public int? jerarBen_4 { get; set; }
        public string? porfBen_4 { get; set; }
        public string? asoBen_5 { get; set; }
        public int? jerarBen_5 { get; set; }
        public string? porfBen_5 { get; set; }
        public string? asoBen_6 { get; set; }
        public int? jerarBen_6 { get; set; }
        public string? porfBen_6 { get; set; }
        public string? otroNombre { get; set; }
        public string? asoBen_Otro { get; set; }
        public int? jerarBen_Otro { get; set; }
        public string? porfBen_Otro { get; set; }
        public string? marcaPan1 { get; set; }
        public string? refPan1 { get; set; }
        public string? usoPanM1 { get; set; }
        public string? usarPanM1 { get; set; }
        public string? marcaPan2 { get; set; }
        public string? refPan2 { get; set; }
        public string? usoPanM2 { get; set; }
        public string? usarPanM2 { get; set; }
        public string? marcaPan3 { get; set; }
        public string? refPan3 { get; set; }
        public string? usoPanM3 { get; set; }
        public string? usarPanM3 { get; set; }
        public string? marcaPan4 { get; set; }
        public string? refPan4 { get; set; }
        public string? usoPanM4 { get; set; }
        public string? usarPanM4 { get; set; }
        public string? marcaPan5 { get; set; }
        public string? refPan5 { get; set; }
        public string? usoPanM5 { get; set; }
        public string? usarPanM5 { get; set; }
        public string? marcaPan6 { get; set; }
        public string? refPan6 { get; set; }
        public string? usoPanM6 { get; set; }
        public string? usarPanM6 { get; set; }
        public string? marcaPan7 { get; set; }
        public string? refPan7 { get; set; }
        public string? usoPanM7 { get; set; }
        public string? usarPanM7 { get; set; }
    }
}
