using System.ComponentModel.DataAnnotations;

namespace InstrumentoT4E0_29.Models
{
    public class MonadicaBDT4E0_29
    {
        public int id { get; set; }
        public string? profesional_2 { get; set; }
        public string? participante { get; set; }
        public int? odenUsoM1 { get; set; }
        public string? semM1 { get; set; }
        public string? semM1Rz1 { get; set; }
        public string? semM1Rz1_1 { get; set; }
        public string? semM1Rz1_2 { get; set; }
        public string? semM1Rz2 { get; set; }
        public string? semM1Rz2_1 { get; set; }
        public string? semM1Rz2_2 { get; set; }
        public string? semM1Rz3 { get; set; }
        public string? semM1Rz3_1 { get; set; }
        public string? semM1Rz3_2 { get; set; }
        public string? semM1Rz4 { get; set; }
        public string? semM1Rz4_1 { get; set; }
        public string? semM1Rz4_2 { get; set; }
        public string? semM1Rz5 { get; set; }
        public string? semM1Rz5_1 { get; set; }
        public string? semM1Rz5_2 { get; set; }
        public string? semM1A { get; set; }
        public int? semM1Ben1 { get; set; }
        public int? semM1Ben2 { get; set; }
        public int? semM1Ben3 { get; set; }
        public int? semM1Ben4 { get; set; }
        public int? semM1Ben5 { get; set; }
        public int? semM1Ben6 { get; set; }
        public string? semM1BenOtroN { get; set; }
        public int? semM1BenOtro { get; set; }
        public string? panM1Dur_1 { get; set; }
        public string? panM1Dur_2 { get; set; }
        public string? panM1Dur_3 { get; set; }
        public string? panM1Dur_4 { get; set; }
        public string? panM1Dur_5 { get; set; }
        public string? panM1Dur_6 { get; set; }
        public string? panM1Dur_7 { get; set; }
        public string? panM1Dur_8 { get; set; }
        public string? panM1Dur_9 { get; set; }
        public string? panM1Dur_10 { get; set; }
        public string? panM1Dur_11 { get; set; }
        public string? panM1Dur_12 { get; set; }
        public string? panM1Dur_13 { get; set; }
        public string? panM1Dur_14 { get; set; }
        public string? panM1Dur_15 { get; set; }
        public string? panM1Dur_16 { get; set; }
        public string? panM1Dur_17 { get; set; }
        public string? panM1Dur_18 { get; set; }
        public int? cantDiaM1_1 { get; set; }
        public int? cantDiaM1_2 { get; set; }
        public int? cantDiaM1_3 { get; set; }
        public int? cantNocheM1_1 { get; set; }
        public int? cantNocheM1_2 { get; set; }
        public int? cantNocheM1_3 { get; set; }
        public string? obsProM1 { get; set; }
        public string? filtM1 { get; set; }
        public int? filtM1No { get; set; }
        public string? filtM1Mom_1 { get; set; }
        public string? filtM1Mom_2 { get; set; }
        public string? filM1Niv { get; set; }
        public string? filM1Carct { get; set; }
        public string? filM1lgr { get; set; }
        public string? filtM1Tipo { get; set; }
        public string? irriM1 { get; set; }
        public string? irriCaractM1 { get; set; }
        public string? irriM1Zon_1 { get; set; }
        public string? irriM1Part_1 { get; set; }
        public string? irriM1Zon_2 { get; set; }
        public string? irriM1Part_2 { get; set; }
        public string? irriM1Zon_3 { get; set; }
        public string? irriM1Part_3 { get; set; }
        public string? tamM1 { get; set; }
        public string? tamM1Tipo_1 { get; set; }
        public string? tamM1Part_1 { get; set; }
        public string? tamM1Tipo_2 { get; set; }
        public string? tamM1Part_2 { get; set; }
        public string? tamM1Tipo_3 { get; set; }
        public string? tamM1Part_3 { get; set; }
        public int? odenUsoM2 { get; set; }
        public string? semM2 { get; set; }
        public string? semM2Rz1 { get; set; }
        public string? semM2Rz1_1 { get; set; }
        public string? semM2Rz1_2 { get; set; }
        public string? semM2Rz2 { get; set; }
        public string? semM2Rz2_1 { get; set; }
        public string? semM2Rz2_2 { get; set; }
        public string? semM2Rz3 { get; set; }
        public string? semM2Rz3_1 { get; set; }
        public string? semM2Rz3_2 { get; set; }
        public string? semM2Rz4 { get; set; }
        public string? semM2Rz4_1 { get; set; }
        public string? semM2Rz4_2 { get; set; }
        public string? semM2Rz5 { get; set; }
        public string? semM2Rz5_1 { get; set; }
        public string? semM2Rz5_2 { get; set; }
        public string? semM2A { get; set; }
        public int? semM2Ben1 { get; set; }
        public int? semM2Ben2 { get; set; }
        public int? semM2Ben3 { get; set; }
        public int? semM2Ben4 { get; set; }
        public int? semM2Ben5 { get; set; }
        public int? semM2Ben6 { get; set; }
        public string? semM2BenOtroN { get; set; }
        public int? semM2BenOtro { get; set; }
        public string? panM2Dur_1 { get; set; }
        public string? panM2Dur_2 { get; set; }
        public string? panM2Dur_3 { get; set; }
        public string? panM2Dur_4 { get; set; }
        public string? panM2Dur_5 { get; set; }
        public string? panM2Dur_6 { get; set; }
        public string? panM2Dur_7 { get; set; }
        public string? panM2Dur_8 { get; set; }
        public string? panM2Dur_9 { get; set; }
        public string? panM2Dur_10 { get; set; }
        public string? panM2Dur_11 { get; set; }
        public string? panM2Dur_12 { get; set; }
        public string? panM2Dur_13 { get; set; }
        public string? panM2Dur_14 { get; set; }
        public string? panM2Dur_15 { get; set; }
        public string? panM2Dur_16 { get; set; }
        public string? panM2Dur_17 { get; set; }
        public string? panM2Dur_18 { get; set; }
        public int? cantDiaM2_1 { get; set; }
        public int? cantDiaM2_2 { get; set; }
        public int? cantDiaM2_3 { get; set; }
        public int? cantNocheM2_1 { get; set; }
        public int? cantNocheM2_2 { get; set; }
        public int? cantNocheM2_3 { get; set; }
        public string? obsProM2 { get; set; }
        public string? filtM2 { get; set; }
        public int? filtM2No { get; set; }
        public string? filtM2Mom_1 { get; set; }
        public string? filtM2Mom_2 { get; set; }
        public string? filM2Niv { get; set; }
        public string? filM2Carct { get; set; }
        public string? filM2lgr { get; set; }
        public string? filtM2Tipo { get; set; }
        public string? irriM2 { get; set; }
        public string? irriCaractM2 { get; set; }
        public string? irriM2Zon_1 { get; set; }
        public string? irriM2Part_1 { get; set; }
        public string? irriM2Zon_2 { get; set; }
        public string? irriM2Part_2 { get; set; }
        public string? irriM2Zon_3 { get; set; }
        public string? irriM2Part_3 { get; set; }
        public string? tamM2 { get; set; }
        public string? tamM2Tipo_1 { get; set; }
        public string? tamM2Part_1 { get; set; }
        public string? tamM2Tipo_2 { get; set; }
        public string? tamM2Part_2 { get; set; }
        public string? tamM2Tipo_3 { get; set; }
        public string? tamM2Part_3 { get; set; }
        public int? odenUsoM3 { get; set; }
        public string? semM3 { get; set; }
        public string? semM3Rz1 { get; set; }
        public string? semM3Rz1_1 { get; set; }
        public string? semM3Rz1_2 { get; set; }
        public string? semM3Rz2 { get; set; }
        public string? semM3Rz2_1 { get; set; }
        public string? semM3Rz2_2 { get; set; }
        public string? semM3Rz3 { get; set; }
        public string? semM3Rz3_1 { get; set; }
        public string? semM3Rz3_2 { get; set; }
        public string? semM3Rz4 { get; set; }
        public string? semM3Rz4_1 { get; set; }
        public string? semM3Rz4_2 { get; set; }
        public string? semM3Rz5 { get; set; }
        public string? semM3Rz5_1 { get; set; }
        public string? semM3Rz5_2 { get; set; }
        public string? semM3A { get; set; }
        public int? semM3Ben1 { get; set; }
        public int? semM3Ben2 { get; set; }
        public int? semM3Ben3 { get; set; }
        public int? semM3Ben4 { get; set; }
        public int? semM3Ben5 { get; set; }
        public int? semM3Ben6 { get; set; }
        public string? semM3BenOtroN { get; set; }
        public int? semM3BenOtro { get; set; }
        public string? panM3Dur_1 { get; set; }
        public string? panM3Dur_2 { get; set; }
        public string? panM3Dur_3 { get; set; }
        public string? panM3Dur_4 { get; set; }
        public string? panM3Dur_5 { get; set; }
        public string? panM3Dur_6 { get; set; }
        public string? panM3Dur_7 { get; set; }
        public string? panM3Dur_8 { get; set; }
        public string? panM3Dur_9 { get; set; }
        public string? panM3Dur_10 { get; set; }
        public string? panM3Dur_11 { get; set; }
        public string? panM3Dur_12 { get; set; }
        public string? panM3Dur_13 { get; set; }
        public string? panM3Dur_14 { get; set; }
        public string? panM3Dur_15 { get; set; }
        public string? panM3Dur_16 { get; set; }
        public string? panM3Dur_17 { get; set; }
        public string? panM3Dur_18 { get; set; }
        public int? cantDiaM3_1 { get; set; }
        public int? cantDiaM3_2 { get; set; }
        public int? cantDiaM3_3 { get; set; }
        public int? cantNocheM3_1 { get; set; }
        public int? cantNocheM3_2 { get; set; }
        public int? cantNocheM3_3 { get; set; }
        public string? obsProM3 { get; set; }
        public string? filtM3 { get; set; }
        public int? filtM3No { get; set; }
        public string? filtM3Mom_1 { get; set; }
        public string? filtM3Mom_2 { get; set; }
        public string? filM3Niv { get; set; }
        public string? filM3Carct { get; set; }
        public string? filM3lgr { get; set; }
        public string? filtM3Tipo { get; set; }
        public string? irriM3 { get; set; }
        public string? irriCaractM3 { get; set; }
        public string? irriM3Zon_1 { get; set; }
        public string? irriM3Part_1 { get; set; }
        public string? irriM3Zon_2 { get; set; }
        public string? irriM3Part_2 { get; set; }
        public string? irriM3Zon_3 { get; set; }
        public string? irriM3Part_3 { get; set; }
        public string? tamM3 { get; set; }
        public string? tamM3Tipo_1 { get; set; }
        public string? tamM3Part_1 { get; set; }
        public string? tamM3Tipo_2 { get; set; }
        public string? tamM3Part_2 { get; set; }
        public string? tamM3Tipo_3 { get; set; }
        public string? tamM3Part_3 { get; set; }
    }
}
